Fix checksumdir not ignoring __pycache__ content (#341)

diff --git a/.github/workflows/notebooks.yaml b/.github/workflows/notebooks.yaml
--- a/.github/workflows/notebooks.yaml
+++ b/.github/workflows/notebooks.yaml
@@ -50,6 +50,18 @@ jobs:
         run: |
           python -m pip install --upgrade pip
           python -m pip install tox tox-gh-actions build
+      - name: Check Dockerfile hash is up-to-date
+        if: github.actor != 'dependabot[bot]'
+        run: |
+          bash -ex .github/scripts/modify_dockerfile.sh
+          changed_hash=$(git status --porcelain binder/Dockerfile)
+          if [ -n "$changed_hash" ]; then
+            echo "ERROR: Dockerfile hash is out of sync!"
+            tree docker
+            grep FROM binder/Dockerfile
+            exit 1
+          fi
+          echo "PASSED: Dockerfile hash is up-to-date!"
       - name: Test Notebooks with Tox
         working-directory: notebooks/tests
         run: tox
